[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_memo_compressed = "5dJnfmrWsRwoDNRfeVN7YsKDCbF6K6DikKcLTjWeF1JR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lucidsamuel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
